- name: Get host information
  hosts: all
  gather_facts: false
  tasks:
      - name: Retrieve IP and username
        ansible.builtin.debug:
            msg: "{{ ansible_host }},{{ ansible_user }}"
        register: host_info

      - name: Save host information
        delegate_to: localhost
        ansible.builtin.copy:
            content: "{{ host_info }}"
            dest: ./temp/host_info.json
            mode: "0644"
