- name: Retrieve IP and username
  ansible.builtin.set_fact:
      host_info: "{{ ansible_host }},{{ ansible_user }}"

- name: Save host information
  delegate_to: localhost
  ansible.builtin.copy:
      content: "{{ host_info }}"
      dest: ../temp/host_info.csv
      mode: "0644"
  # don't sudo as we are on the local machine
  become: false
